services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.client
      args:
        - API_HOST=backend
        - API_PORT=5000
    image: footballstats.client        
    container_name: footballstats-client-container
    ports:
      - "80:80"
    networks:
      - internal

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.api      
      args:
        - PORT=5000
        - DB_CONNECTION_STRING=Host=db;Port=5432;Database=footballstats;Username=postgres;Password=postgres
    image: footballstats.api
    container_name: footballstats-api-container
    ports:
      - "5000:5000"
    networks:
      - internal

  db:
    build:
      context: .
      dockerfile: Dockerfile.psql        
    image: footballstats.db
    container_name: footballstats-db-container  
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres  
      PGDATA: /var/lib/postgresql/data/pgdata    
    ports:
      - 5432:5432  # Expose PostgreSQL port, use a non-standard port to avoid interfering with the local PostgreSQL server
    networks:
      - internal

networks:
  internal: