services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.client
      args:
        - API_HOST=backend
        - API_PORT=5000
    image: footballstats.client        
    container_name: footballstats-client-container
    env_file:       
      - path: .env  
        required: false        
    ports:
      - ${APP_PORT:-80}:80
    networks:
      - internal

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.api      
      args:
        - PORT=5000
        - DB_CONNECTION_STRING=Host=db;Port=5432;Database=footballstats;Username=postgres;Password=postgres
    image: footballstats.api
    container_name: footballstats-api-container
    
    networks:
      - internal

  db:
    build:
      context: .
      dockerfile: Dockerfile.psql        
    image: footballstats.db
    container_name: footballstats-db-container  
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres  
      PGDATA: /var/lib/postgresql/data/pgdata    
    
    networks:
      - internal

networks:
  internal: